'use client';

import { CreativePreview } from '@/components/CreativePreview';
import { CampaignPageLoader } from '@/components/CampaignPageLoader';
import { useCampaign } from '@/hooks/useCampaign';

export default function CreativePage() {
  const { campaign, loading } = useCampaign();

  return (
    <CampaignPageLoader
      loading={loading}
      campaign={campaign}
      title="Creative Assets"
      emptyMessage="Launch a campaign from the home page to see generated creatives."
    >
      {(c) => (
        <>
          <p className="text-muted-foreground -mt-4 mb-4">Generated by CreativeAgent — Design Team</p>
          <CreativePreview creatives={c.creatives} />
        </>
      )}
    </CampaignPageLoader>
  );
}
