'use client';

import { AnimatedCard } from '@/components/AnimatedCard';
import { CampaignPageLoader } from '@/components/CampaignPageLoader';
import { useCampaign } from '@/hooks/useCampaign';

export default function InvestorPage() {
  const { campaign, loading } = useCampaign();

  return (
    <CampaignPageLoader
      loading={loading}
      campaign={campaign}
      title="Investor Summary"
      emptyMessage="Launch a campaign from the home page to see investor analysis."
    >
      {(c) => {
        const summary = c.investorSummary;
        const payments = c.payments;
        return (
          <>
            <p className="text-muted-foreground -mt-4 mb-4">
              Generated by InvestorAgent — Seedcamp + Blue Wire Capital
            </p>

            {summary && (
              <AnimatedCard>
                <h2 className="text-lg font-semibold text-indigo-400 mb-4">Financial Overview</h2>
                <div className="grid md:grid-cols-4 gap-4 mb-6">
                  <div className="text-center p-4 bg-muted/50 rounded-lg">
                    <p className="text-2xl font-bold">${summary.totalSpend.toLocaleString()}</p>
                    <p className="text-xs text-muted-foreground">Total Spend</p>
                  </div>
                  <div className="text-center p-4 bg-muted/50 rounded-lg">
                    <p className="text-2xl font-bold text-green-400">{summary.projectedROI}x</p>
                    <p className="text-xs text-muted-foreground">Projected ROI</p>
                  </div>
                  <div className="text-center p-4 bg-muted/50 rounded-lg">
                    <p className="text-2xl font-bold">{summary.breakEvenDays}d</p>
                    <p className="text-xs text-muted-foreground">Break Even</p>
                  </div>
                  <div className="text-center p-4 bg-muted/50 rounded-lg">
                    <p className="text-2xl font-bold">{(summary.riskScore * 100).toFixed(0)}%</p>
                    <p className="text-xs text-muted-foreground">Risk Score</p>
                  </div>
                </div>
                <p className="text-sm mb-4"><strong>Recommendation:</strong> {summary.recommendation}</p>
                <ul className="list-disc list-inside text-sm text-muted-foreground">
                  {summary.highlights.map((h, i) => <li key={i}>{h}</li>)}
                </ul>
              </AnimatedCard>
            )}

            {c.finance && (
              <AnimatedCard>
                <h2 className="text-lg font-semibold text-cyan-400 mb-4">
                  Seapoint Financial Control
                </h2>
                <div className="grid md:grid-cols-4 gap-4">
                  <div className="text-center p-4 bg-muted/50 rounded-lg">
                    <p className="text-2xl font-bold">${c.finance.currentCash.toLocaleString()}</p>
                    <p className="text-xs text-muted-foreground">Consolidated Cash</p>
                  </div>
                  <div className="text-center p-4 bg-muted/50 rounded-lg">
                    <p className="text-2xl font-bold">${c.finance.monthlyBurn.toLocaleString()}</p>
                    <p className="text-xs text-muted-foreground">Monthly Burn</p>
                  </div>
                  <div className="text-center p-4 bg-muted/50 rounded-lg">
                    <p className="text-2xl font-bold">{c.finance.runwayMonths} mo</p>
                    <p className="text-xs text-muted-foreground">Cash Runway</p>
                  </div>
                  <div className="text-center p-4 bg-muted/50 rounded-lg">
                    <p className="text-2xl font-bold text-yellow-400">
                      {c.finance.pendingApprovals}
                    </p>
                    <p className="text-xs text-muted-foreground">Approvals Needed</p>
                  </div>
                </div>
              </AnimatedCard>
            )}

            {payments.length > 0 && (
              <AnimatedCard>
                <h2 className="text-lg font-semibold text-purple-400 mb-4">PaymentAgent Transactions</h2>
                <div className="space-y-2">
                  {payments.map((p) => (
                    <div key={p.id} className="flex justify-between items-center p-3 bg-muted/50 rounded-lg text-sm">
                      <div>
                        <span className="font-medium capitalize">{p.type}</span>
                        <span className="text-muted-foreground ml-2">{p.id.slice(0, 16)}...</span>
                      </div>
                      <div className="text-right">
                        <p className="font-bold">${p.amount.toFixed(2)} {p.currency}</p>
                        <p className="text-xs text-muted-foreground capitalize">{p.status}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </AnimatedCard>
            )}

            {c.feedback.length > 0 && (
              <AnimatedCard>
                <h2 className="text-lg font-semibold mb-4">Customer Feedback (Wassist)</h2>
                {c.feedback.map((f, i) => (
                  <div key={i} className="p-3 bg-muted/50 rounded-lg mb-2 text-sm">
                    <span className={`text-xs font-medium uppercase ${
                      f.sentiment === 'positive' ? 'text-green-400' :
                      f.sentiment === 'negative' ? 'text-red-400' : 'text-yellow-400'
                    }`}>{f.sentiment}</span>
                    <p className="mt-1">{f.comment}</p>
                    <p className="text-xs text-muted-foreground mt-1">{f.source}</p>
                  </div>
                ))}
              </AnimatedCard>
            )}
          </>
        );
      }}
    </CampaignPageLoader>
  );
}
